#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.Reporting.Templates
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class @__Export : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 4 "..\..\Reporting\Templates\__Export.cshtml"

    public Scheduler.Reporting.Report Report { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n<html>\r\n<head>\r\n    <style type=\"text/css\">\r\n\r\n        .PageBreak {\r\n        " +
"    page-break-after: always;\r\n        }\r\n\r\n        table tr td {\r\n            v" +
"ertical-align: top;\r\n        }\r\n\r\n        .Calendar {\r\n            clear:both;\r\n" +
"        }\r\n\r\n        .Day {\r\n            height: 50px;\r\n            max-height: " +
"50px;\r\n            min-height: 50px;\r\n            width: 50px;\r\n            max-" +
"width: 50px;\r\n            min-width: 50px;\r\n            float: left;\r\n          " +
"  border: 1px solid gray;\r\n            position: relative;\r\n        }\r\n\r\n       " +
" .PinkDay {\r\n            background-color: pink;\r\n            height: 100%;\r\n   " +
"         float: left;\r\n        }\r\n\r\n        .BlueDay {\r\n            background-c" +
"olor: lightskyblue;\r\n            height: 100%;\r\n            float: left;\r\n      " +
"  }\r\n\r\n        .UnknownDay {\r\n            background-color: silver;\r\n           " +
" height: 100%;\r\n            float: left;\r\n        }\r\n\r\n\r\n        .DayLabel {\r\n  " +
"          position: absolute;\r\n            right: 10px;\r\n            top: 10px;\r" +
"\n        }\r\n\r\n        .DaysOfWeek div {\r\n            height: 50px;\r\n            " +
"max-height: 50px;\r\n            min-height: 50px;\r\n            width: 50px;\r\n    " +
"        max-width: 50px;\r\n            min-width: 50px;\r\n                float: l" +
"eft;\r\n            border: 1px solid gray;\r\n            position: relative;\r\n    " +
"        text-align: center;\r\n            font-size: 48px;\r\n        }\r\n\r\n        " +
".h1 {\r\n            font-size: 64px;\r\n        }\r\n\r\n        .Week {\r\n            c" +
"lear: both;\r\n        }\r\n\r\n        .DayView {\r\n            float:left;\r\n        }" +
"\r\n\r\n        .MonthView {\r\n            float: left;\r\n        }\r\n\r\n        .MonthV" +
"iew table thead tr td {\r\n\t        font-weight: bold;\r\n            padding-left: " +
"20px;\r\n        }\r\n\r\n        .MonthView table tbody tr td {\r\n\t        padding-lef" +
"t: 20px;\r\n        }\r\n\r\n\r\n        .UnknownBox {\r\n            background-color: si" +
"lver;\r\n            margin-right: 5px;\r\n            float: left;\r\n            hei" +
"ght:     15px;\r\n            max-height: 15px;\r\n            min-height: 15px;\r\n  " +
"          width:      15px;\r\n            max-width:  15px;\r\n            min-widt" +
"h:  15px;\r\n            border: 1px solid gray;\r\n        }\r\n\r\n        .PinkBox {\r" +
"\n            background-color: pink;\r\n            margin-right: 5px;\r\n          " +
"  float: left;\r\n            height:     15px;\r\n            max-height: 15px;\r\n  " +
"          min-height: 15px;\r\n            width:      15px;\r\n            max-widt" +
"h:  15px;\r\n            min-width:  15px;\r\n            border: 1px solid gray;\r\n " +
"           \r\n        }\r\n\r\n        .BlueBox {\r\n            background-color: ligh" +
"tskyblue;\r\n            margin-right: 5px;\r\n            float: left;\r\n           " +
" height:     15px;\r\n            max-height: 15px;\r\n            min-height: 15px;" +
"\r\n            width:      15px;\r\n            max-width:  15px;\r\n            min-" +
"width:  15px;\r\n            border: 1px solid gray;\r\n\r\n        }\r\n\r\n    </style>\r" +
"\n</head>\r\n<body>\r\n\r\n");


            
            #line 146 "..\..\Reporting\Templates\__Export.cshtml"
Write(Report.ToHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n</body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
