#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.Reporting.Templates
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Reporting\Templates\CalendarDayActivityView.cshtml"
    using Scheduler;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Reporting\Templates\CalendarDayActivityView.cshtml"
    using Scheduler.Reporting.Templates;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class CalendarDayActivityView : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 7 "..\..\Reporting\Templates\CalendarDayActivityView.cshtml"

    public double Duration { get; set; }
    public ParentingAssignment Owner { get; set; }

    public string Description { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n<div class=\"");


            
            #line 14 "..\..\Reporting\Templates\CalendarDayActivityView.cshtml"
        Write(Owner);

            
            #line default
            #line hidden
WriteLiteral("Day\" style=\"width: ");


            
            #line 14 "..\..\Reporting\Templates\CalendarDayActivityView.cshtml"
                                   Write(Duration * 100);

            
            #line default
            #line hidden
WriteLiteral("%;\" title=\"");


            
            #line 14 "..\..\Reporting\Templates\CalendarDayActivityView.cshtml"
                                                              Write(Description);

            
            #line default
            #line hidden
WriteLiteral("\"></div>\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
