#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.Reporting.Templates
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Reporting\Templates\CalendarMonthView.cshtml"
    using Scheduler;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Reporting\Templates\CalendarMonthView.cshtml"
    using Scheduler.Reporting.Templates;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class CalendarMonthView : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 7 "..\..\Reporting\Templates\CalendarMonthView.cshtml"

    public Scheduler.Reporting.MonthReport Report { get; set; }


        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n");


            
            #line 12 "..\..\Reporting\Templates\CalendarMonthView.cshtml"
  
    var Weeks = new List<CalendarWeekView>();

    var FirstDayOfMonth = new DateTime(Report.Year, Report.Month, 1);
    var DaysInMonth = DateTime.DaysInMonth(Report.Year, Report.Month);
    var LastDay = new DateTime(Report.Year, Report.Month, DaysInMonth);

    var Backup = FirstDayOfMonth;

    var CurrentWeek = new CalendarWeekView();
    Weeks.Add(CurrentWeek);

    foreach (var item in Report.Reports) {
        if (CurrentWeek.Days.Count != 0 && new DateTime(item.Year, item.Month, item.Day).DayOfWeek == DayOfWeek.Sunday) {
            CurrentWeek = new CalendarWeekView();
            Weeks.Add(CurrentWeek);
        }
        CurrentWeek.Days.Add(item);
    }


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"DayView\">\r\n    <div class=\"DaysOfWeek\">\r\n        <div>S</div>\r\n    " +
"    <div>M</div>\r\n        <div>T</div>\r\n        <div>W</div>\r\n        <div>R</di" +
"v>\r\n        <div>F</div>\r\n        <div>S</div>\r\n    </div>\r\n");


            
            #line 43 "..\..\Reporting\Templates\CalendarMonthView.cshtml"
     foreach (var item in Weeks) {
        
            
            #line default
            #line hidden
            
            #line 44 "..\..\Reporting\Templates\CalendarMonthView.cshtml"
   Write(item.TransformText());

            
            #line default
            #line hidden
            
            #line 44 "..\..\Reporting\Templates\CalendarMonthView.cshtml"
                             
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");


        }
    }
}
#pragma warning restore 1591
