#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.Reporting.Templates
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 5 "..\..\Reporting\Templates\CompleteReportOutput.cshtml"
    using Scheduler;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Reporting\Templates\CompleteReportOutput.cshtml"
    using Scheduler.Reporting.Templates;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class CompleteReportOutput : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 8 "..\..\Reporting\Templates\CompleteReportOutput.cshtml"

    public Scheduler.Reporting.CompleteReport Report { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n");


WriteLiteral(@"

<h1>
    The Complete Parenting Plan for [FAMILY]
</h1>
<div>
    This document is the complete parenting plan for [FAMILY]. <br />
    It is generated by using the following rules:<br />
    <br />
    [Show the rules ]<br />
    <br />
    It was generated for the following dates:<br />
    [DATES]<br />
    <br />
    The following describes parenting time allotment:<br />
</div>


");


            
            #line 28 "..\..\Reporting\Templates\CompleteReportOutput.cshtml"
  
    var Overnights = new OvernightCalculationsView();
    Overnights.Overnights = Report.Overnights;


            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 33 "..\..\Reporting\Templates\CompleteReportOutput.cshtml"
Write(Overnights.TransformText());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div class=\"PageBreak\"></div>\r\n\r\n");


            
            #line 37 "..\..\Reporting\Templates\CompleteReportOutput.cshtml"
 foreach (var item in Report.Reports) {
    
            
            #line default
            #line hidden
            
            #line 38 "..\..\Reporting\Templates\CompleteReportOutput.cshtml"
Write(item.ToHtml());

            
            #line default
            #line hidden
            
            #line 38 "..\..\Reporting\Templates\CompleteReportOutput.cshtml"
                  
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
