#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.Reporting.Templates
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Reporting\Templates\OvernightCalculationsView.cshtml"
    using Scheduler;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class OvernightCalculationsView : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 7 "..\..\Reporting\Templates\OvernightCalculationsView.cshtml"

    public Dictionary<ParentingAssignment, int> Overnights { get; set; }

    private class AssignmentInfo {
        public Scheduler.ParentingAssignment Assignment { get; set; }
        public int Days { get; set; }
    }

    private AssignmentInfo Overnights_Most { get; set; }
    private AssignmentInfo Overnights_Least { get; set; }
    private AssignmentInfo Overnights_Difference { get; set; }

    private int GetPercentage(double Top, double Bottom) {
        double ret = 0;

        if(Bottom > 0) {
            ret = Top * 100 / Bottom ;
        }

        return (int)Math.Round(ret);
    }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n");


WriteLiteral("\r\n\r\n");


            
            #line 30 "..\..\Reporting\Templates\OvernightCalculationsView.cshtml"
  
    var Pink = new AssignmentInfo() {
        Assignment = Scheduler.ParentingAssignment.Pink,
        Days = Overnights[Scheduler.ParentingAssignment.Pink]
    };

    var Blue = new AssignmentInfo() {
        Assignment = Scheduler.ParentingAssignment.Blue,
        Days = Overnights[Scheduler.ParentingAssignment.Blue]
    };

    Overnights_Difference = new AssignmentInfo();

    Overnights_Difference.Assignment = (Pink.Days >= Blue.Days ? Pink.Assignment : Blue.Assignment);
    Overnights_Difference.Days = Math.Abs(Pink.Days - Blue.Days);

    Overnights_Most = (Pink.Days >= Blue.Days ? Pink : Blue);
    Overnights_Least = (Pink.Days < Blue.Days ? Pink : Blue);

    var TotalDays = Pink.Days + Blue.Days;


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<table>\r\n    <tr>\r\n        <td><div class=\"");


            
            #line 55 "..\..\Reporting\Templates\OvernightCalculationsView.cshtml"
                    Write(Overnights_Most.Assignment);

            
            #line default
            #line hidden
WriteLiteral("Box\"></div></td>\r\n        <td align=\"right\">");


            
            #line 56 "..\..\Reporting\Templates\OvernightCalculationsView.cshtml"
                     Write(Overnights_Most.Days);

            
            #line default
            #line hidden
WriteLiteral(" Overnights</td>\r\n        <td>(");


            
            #line 57 "..\..\Reporting\Templates\OvernightCalculationsView.cshtml"
        Write(GetPercentage(Overnights_Most.Days, Overnights_Most.Days + Overnights_Least.Days));

            
            #line default
            #line hidden
WriteLiteral("%)</td>\r\n    </tr>\r\n    <tr>\r\n        <td><div class=\"");


            
            #line 60 "..\..\Reporting\Templates\OvernightCalculationsView.cshtml"
                    Write(Overnights_Least.Assignment);

            
            #line default
            #line hidden
WriteLiteral("Box\"></div></td>\r\n        <td align=\"right\">");


            
            #line 61 "..\..\Reporting\Templates\OvernightCalculationsView.cshtml"
                     Write(Overnights_Least.Days);

            
            #line default
            #line hidden
WriteLiteral(" Overnights</td>\r\n        <td>(");


            
            #line 62 "..\..\Reporting\Templates\OvernightCalculationsView.cshtml"
        Write(GetPercentage(Overnights_Least.Days, Overnights_Most.Days + Overnights_Least.Days));

            
            #line default
            #line hidden
WriteLiteral("%)</td>\r\n    </tr>\r\n    <tr>\r\n        <td colspan=\"3\">\r\n            <hr />\r\n     " +
"   </td>\r\n    </tr>\r\n    <tr>\r\n        <td><div class=\"");


            
            #line 70 "..\..\Reporting\Templates\OvernightCalculationsView.cshtml"
                    Write(Overnights_Difference.Assignment);

            
            #line default
            #line hidden
WriteLiteral("Box\"></div></td>\r\n        <td align=\"right\">");


            
            #line 71 "..\..\Reporting\Templates\OvernightCalculationsView.cshtml"
                     Write(Overnights_Difference.Days);

            
            #line default
            #line hidden
WriteLiteral(" Overnights</td>\r\n        <td>(");


            
            #line 72 "..\..\Reporting\Templates\OvernightCalculationsView.cshtml"
        Write(GetPercentage(Overnights_Difference.Days, Overnights_Most.Days + Overnights_Least.Days));

            
            #line default
            #line hidden
WriteLiteral("% More)</td>\r\n    </tr>\r\n</table>");


        }
    }
}
#pragma warning restore 1591
