#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.Reporting.Templates
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 5 "..\..\Reporting\Templates\YearReportView.cshtml"
    using Scheduler;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Reporting\Templates\YearReportView.cshtml"
    using Scheduler.Reporting.Templates;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class YearReportView : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 8 "..\..\Reporting\Templates\YearReportView.cshtml"

    public Scheduler.Reporting.YearReport Report { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n<h1>\r\n    Parenting Plan Report for ");


            
            #line 13 "..\..\Reporting\Templates\YearReportView.cshtml"
                         Write(Report.Year);

            
            #line default
            #line hidden
WriteLiteral("\r\n</h1>\r\n\r\n<div>\r\n    The following parenting plan allotment is an aggregate of t" +
"he entire year of ");


            
            #line 17 "..\..\Reporting\Templates\YearReportView.cshtml"
                                                                            Write(Report.Year);

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n");


            
            #line 20 "..\..\Reporting\Templates\YearReportView.cshtml"
   
    var Overnights = new OvernightCalculationsView();
    Overnights.Overnights = Report.Overnights;


            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 25 "..\..\Reporting\Templates\YearReportView.cshtml"
Write(Overnights.TransformText());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div class=\"PageBreak\"></div>\r\n\r\n");


            
            #line 29 "..\..\Reporting\Templates\YearReportView.cshtml"
 foreach (var item in Report.Reports) {
    
            
            #line default
            #line hidden
            
            #line 30 "..\..\Reporting\Templates\YearReportView.cshtml"
Write(item.ToHtml());

            
            #line default
            #line hidden
            
            #line 30 "..\..\Reporting\Templates\YearReportView.cshtml"
                  
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
